print("Meu\nnome\né\nSilva.", end=" ")
print("Jahaziel Pomahuallca Silva.")
print()
print("Hoje estou comprometido com o projeto que me ajudará para", "trasformar.")
print()
print("Ese projeto visa em ter mais tempo com minha família.")
